I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 10, in script
    show misha right
Exception: Image 'misha' does not accept attributes 'right'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 10, in script
    show misha right
  File "/home/alex/Apps/RenPy/renpy/ast.py", line 1117, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/home/alex/Apps/RenPy/renpy/ast.py", line 1080, in show_imspec
    renpy.config.show(name,
  File "/home/alex/Apps/RenPy/renpy/exports/displayexports.py", line 477, in show
    if not base.find_target() and renpy.config.missing_show:
  File "/home/alex/Apps/RenPy/renpy/display/image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "/home/alex/Apps/RenPy/renpy/display/displayable.py", line 249, in _duplicate
    args.extraneous()
  File "/home/alex/Apps/RenPy/renpy/display/displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'misha' does not accept attributes 'right'.

Linux-6.8.0-53-generic-x86_64-with-glibc2.39 x86_64
Ren'Py 8.3.4.24120703
Cerebral_VN_Demo 1.0
Sun Feb 23 17:59:34 2025
